import type { Metadata } from 'next'
import Navbar from '@/components/navbar'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootswatch/dist/flatly/bootstrap.min.css'
import '../styles/globals.css'

export const metadata: Metadata = {
	title: 'BK Web Developer',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
